### ISSUE TITLE
Implement general rotation algorithm

### ISSUE THREAD

**Issue by zbstof** [PashaBeshchuk/tetris#16]
Depends on #9 and #15.

In order to implement general rotation algorithm, we need to combine existing helper methods.
First implementation will not care about the position of tetromino relative to edges of the field and blocks on the field (no problems when coordinates are less than zero or more than size of the field or when rotation results overlaps blocks already placed on the field).

- Create some type of tetromino graphically in some rotational phase (buildTetromino/getCoordinates)
- Determine top-left corner of tetromino (calculatorCoordinateOfTopLeft)
- Rotate tetromino counter-clockwise around the top-left corner (rotatesArrayOfCoordinates)
- Determine left-right and top-bottom shift amount (determineShift)
- Shift tetromino coordinates this amount (shiftCoordinates)

## determineShift(typeOfTetromino, rotationPhaseOfTetromino)

In order to determine shift amount, you need additional helper function:
Parameters: 
- typeOfTetromino - I, O, Z, S, J, L or T (1)
- rotationPhaseOfTetromino - single value representing current phase of tetromino. Dor example I-tetromino can be "vertical" or "horizontal" (2)

This function should return (x,y)-object representing by how much each element of tetromino should be shifted

## rotateTetromino(typeOfTetromino, rotationPhaseOfTetromino, tetrominoCoordinates)

Using this function, combine all the steps into final function:
Parameters:
- typeOfTetromino (same as above)
- rotationPhaseOfTetromino (same as above)
- tetrominoCoordinates - array of coordinate objects (x,y), which represents actual coordinates

Function should return new array of coordinates.
Resulting array should be sorted.
Function should use algorithm described at the top of the issue.

Write unit tests for function rotateTetromino for _every_ possible input of typeOfTetromino and rotationPhaseOfTetromino. Only one tetrominoCoordinates is needed per combination.
Examples:
- O-tetromino, one rotation
- T-tetromino, with "nose" pointing up, down, left, right
- I-tetromino, horizontal and vertical, one rotation each
- etc.

tetrominoCoordinates and expected result should be represented graphically

## incrementPhase(typeOfTetromino, currentRotationPhaseOfTetromino)

Because rotateTetromino accepts rotationPhaseOfTetromino externally, we need another helper function to update rotation phase.
Function accepts 2 parameters
- typeOfTetromino (same as above)
- currentRotationPhaseOfTetromino (same as above)

This function returns new rotation phase.

- If currentRotationPhaseOfTetromino is the last one, we should return return first phase possible
- If currentRotationPhaseOfTetromino is _not_ the last one, we return next rotation phase

Example:
typeOfTetromino - I
currentRotationPhaseOfTetromino - horizontal
return - vertical
Example 2:
typeOfTetromino - T
currentRotationPhaseOfTetromino - "nose" pointing to the right
return - "nose" pointing to the top

Cover all combinations of typeOfTetromino and currentRotationPhaseOfTetromino with unit tests.

**Comment by PashaBeshchuk** [comment]
rotationPhaseOfTetromino - it is function witch return array coordinates or function witch return present state tetramino?

**Comment by zbstof** [comment]
rotationPhaseOfTetromino is not a function, but a parameter

**Comment by zbstof** [comment]
Also please note, that I clarified the definition of rotationPhaseOfTetromino
